### ISSUE TITLE
localhost:3000 doesn't show the page

### ISSUE THREAD

**Issue by marcelopalin** [modulr/laravel-scaffold#10]
Congratulations on the initiative and for the project.

I can only access the project when I run 'php artisan serve' with 'localhost: 8000'. 

I am not able to access the project for development by 'localhost: 3000'. It loads and does not show the page ..

Would you help me?

**Comment by alfredobarron** [comment]
Hello @marcelopalin, thanks for used the project I hope will useful for you. Do you run npm install and npm run watch commands?

**Comment by marcelopalin** [comment]
Hello @alfredobarron ! Yes, I did. 

You're running successfully! This is the output:

~/www/2019_projs/laravel-scaffold$ npm run watch

> @ watch /home/mpi/www/2019_projs/laravel-scaffold
> npm run development -- --watch


> @ development /home/mpi/www/2019_projs/laravel-scaffold
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

 10% building modules 1/1 modules 0 active                                         
Webpack is watching the files…

 95% emittingTotal precache size is about 5.68 MB for 33 resources.                     


 DONE  Compiled successfully in 8797ms                                                                                                                                                                                                 14:05:28

                                                                                              Asset     Size  Chunks                    Chunk Names
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.svg?b5472631dbace30d549357ec325b9c62   648 kB          [emitted]  [big]  
              fonts/vendor/simple-line-icons/Simple-Line-Icons.eot?f33df365d6d0255b586f2920355e94d7  54.3 kB          [emitted]         
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.eot?7422060ca379ee9939d3b687d072acad  40.6 kB          [emitted]         
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.eot?70e65a7d34902f2c350816ecfe2f6492   181 kB          [emitted]         
            fonts/vendor/simple-line-icons/Simple-Line-Icons.woff2?0cb0b9c589c0624c9c78dd3d83e946f6  30.1 kB          [emitted]         
              fonts/vendor/simple-line-icons/Simple-Line-Icons.ttf?d2285965fe34b05465047401b8595dd0  54.1 kB          [emitted]         
             fonts/vendor/simple-line-icons/Simple-Line-Icons.woff?78f07e2c2a535c26ef21d95e41bd7175  81.3 kB          [emitted]         
              fonts/vendor/simple-line-icons/Simple-Line-Icons.svg?2fe2efe63441d830b1acd106c1fe8734   239 kB          [emitted]         
 fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff2?48461ea4e797c9774dabb4a0440d2f56  65.3 kB          [emitted]         
  fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.woff?7b464e274bc331f9a765d765359635a5  76.3 kB          [emitted]         
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.ttf?947b9537bc0fecc8130d48eb753495a1   118 kB          [emitted]         
   fonts/vendor/@fortawesome/fontawesome-free/webfa-brands-400.eot?9b6c8da3c489424e2b3e9c9fb6314b37   119 kB          [emitted]         
fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff2?949a2b066ec37f5a384712fc7beaf2f1  14.9 kB          [emitted]         
 fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.woff?381af09a1366b6c2ae65eac5dd6f0588  18.2 kB          [emitted]         
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.ttf?73fe7f1effbf382f499831a0a9f18626  40.3 kB          [emitted]         
  fonts/vendor/@fortawesome/fontawesome-free/webfa-regular-400.svg?b5a61b229c9c92a6ac21f5b0e3c6e9f1   142 kB          [emitted]         
  fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff2?14a08198ec7d1eb96d515362293fed36  67.4 kB          [emitted]         
   fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.woff?815694de1120d6c1e9d1f0895ee81056  86.9 kB          [emitted]         
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.ttf?0079a0ab6bec4da7d6e16f2a2e87cd71   181 kB          [emitted]         
    fonts/vendor/@fortawesome/fontawesome-free/webfa-solid-900.svg?38508b2e7fac045869a86a15936433f7   681 kB          [emitted]  [big]  
                                                                                         /js/app.js  2.05 MB       0  [emitted]  [big]  /js/app
                                                                                       /css/app.css   503 kB       0  [emitted]  [big]  /js/app
[Browsersync] Proxying: http://laravel-scaffold.test
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.119:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 --------------------------------------
[Browsersync] Watching files...

Everything looks ok! But when I try to access 'localhost: 3000' nothing appears.

**Comment by alfredobarron** [comment]
I thing you have a problem with the server, emitted the building files, check the error in this code lines

/js/app.js 2.05 MB 0 [emitted] [big] /js/app
/css/app.css 503 kB 0 [emitted] [big] /js/app

**Comment by marcelopalin** [comment]
The problem still continues ... I tried to mount on windows too, but I could not succeed. It seems to be something with browserSync.

But without problems, the project is fantastic. Every time I need it I compile again with 'npm run dev' and everything works!

**Comment by alfredobarron** [comment]
Edit the webpack.mix.js file, in the param browserSync write your URL that works.

`mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .browserSync('yourdomain.test');`
