### ISSUE TITLE
Sidebar nav links don't show

### ISSUE THREAD

**Issue by shahdsideek** [modulr/laravel-scaffold#12]
Hi, when trying to clone and setup project, I think theres a bug because sidebar nav links don't display.

**Comment by alfredobarron** [comment]
Hi @shahdsideek thanks for used the scaffold,

Do you have a screenshot of bug?

**Comment by shahdsideek** [comment]
<img width="1440" alt="Screen Shot 2019-09-26 at 2 38 19 pm" src="https://user-images.githubusercontent.com/55658991/65658512-7163d000-e06b-11e9-9e4c-755c088241be.png">

sidebar navs dont display also profile icon on top right is broken.

**Comment by shahdsideek** [comment]
The github repository is not the same as the demo, is it possible to fix? Thanks :)

**Comment by alfredobarron** [comment]
Check the roles and the permissions

**Comment by shahdsideek** [comment]
Ok that worked thanks, what about broken profile image?

**Comment by alfredobarron** [comment]
That's good!!
Check the permissions to storage folder
